---
#############################################################################################
# This role creates value file for the deployment of chaincode instantiaition
#############################################################################################

############################################################################################
# Create value file for chaincode invokation
- name: "Create value file for chaincode invokation"
  include_tasks: valuefile.yaml
  vars:
    channelcreator_query: "participants[?org_status=='new']"
    org_query: "organizations[?name=='{{participant.name}}']"
    org: "{{ network | json_query(org_query) | first }}"
  loop: "{{ item | json_query(channelcreator_query) }}"
  loop_control:
    loop_var: participant
