#############################################################################################
# This role generates crypto material for orderers.
#############################################################################################

- name: Call orderercheck.yaml for orderer
  include_tasks: orderercheck.yaml

- name: Call orderer.yaml for each orderer
  include_tasks: orderer.yaml
  loop: "{{ services.orderers }}"
  loop_control:
    loop_var: orderer
