---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: ambassador-admin
  name: ambassador-admin
  namespace: default
spec:
  type: ClusterIP
  ports:
  - name: ambassador-admin
    port: 80
    targetPort: 8877
  selector:
    service: ambassador
---
apiVersion: v1
kind: Service
metadata:
  name: ambassador
  namespace: default
  {{- if .Values.ambassador.eip }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-eip-allocations: {{ .Values.ambassador.eip }}
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind:  Module
      name:  ambassador
      config:
        use_proxy_proto: true
        use_remote_address: false
  {{- end }}
  {{- if .Values.ambassador.grpc }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind:  Module
      name:  ambassador
      config:
        enable_grpc_http11_bridge: true
        enable_grpc_web: true
        use_remote_address: false
        x_forwarded_proto_redirect: true
  {{- end }}
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
   - port: {{ .Values.ambassador.port }}
     name: webhttps
     targetPort: {{ .Values.ambassador.targetPort }}
{{- if .Values.ambassador.otherPorts }}
{{- range .Values.ambassador.otherPorts }}
   - port: {{ . }}
     name: port-{{- . }}
     targetPort: {{ . }}
{{- end }}
{{- end }}
  selector:
    service: ambassador