# This task registers a temporary directory
- name: Register temporary directory
  tempfile:
    state: directory
  register: tmp_directory

# This task checks if the istanbul-tools is already in place or not
- name: Check istanbul
  stat:
    path: "{{ bin_install_dir }}/istanbul"
  register: istanbul_stat_result

# This task clones the istanbul-tools git repository
- name: Clone the istanbul-tools git repo
  git:
    repo: "{{ istanbul.repo }}"
    version: master
    dest: "{{ tmp_directory.path }}"
  when: istanbul_stat_result.stat.exists == False

# This task builds the istanbul binary
- name: Make istanbul
  shell: |
    cd "{{ tmp_directory.path }}"
    make 
  when: istanbul_stat_result.stat.exists == False

# This task creates the bin directory, if it doesn't exist, for storing the istanbul binary
- name: Create bin directory
  file:
    path: "{{ bin_install_dir }}"
    state: directory
    recurse: yes
  when: istanbul_stat_result.stat.exists == False

# This task puts the istanbul binary to above created bin directory
- name: Copy istanbul binary to destination directory
  copy:
    src: "{{ tmp_directory.path }}/build/bin/istanbul"
    dest: "{{ bin_install_dir }}/istanbul"
    mode: 0755
    remote_src: yes
  when: istanbul_stat_result.stat.exists == False
