---
  - name: register temporary directory
    tempfile:
      state: directory
    register: tmp_directory
    tags:
      - molecule-idempotence-notest

  - name: check kubectl
    stat:
      path: "{{ kubectl.bin_directory }}/kubectl"
    register: kubectl_stat_result
    tags:
      - kubectl

  - name: Download kubectl binary
    get_url:
      url: "https://dl.k8s.io/v{{ kubectl.version }}/kubernetes-client-{{ kubectl.os }}-{{ kubectl.arch }}.tar.gz"
      dest: "{{ tmp_directory.path }}"
      checksum: "{{ kubectl.checksum }}"
    when: not kubectl_stat_result.stat.exists
    tags:
      - kubectl

  - name: Unarchive kubernetes-client
    unarchive:
      src: "{{ tmp_directory.path }}/kubernetes-client-{{ kubectl.os }}-{{ kubectl.arch }}.tar.gz"
      dest: "{{ tmp_directory.path }}"
    when: not kubectl_stat_result.stat.exists
    tags:
      - kubectl

  - name: create bin directory
    file:
      path: "{{ kubectl.bin_directory }}"
      state: directory
      recurse: yes
    when: not kubectl_stat_result.stat.exists
    tags:
      - kubectl

  - name: Copy kubectl binary to destination directory
    copy:
      src: "{{ tmp_directory.path }}/kubernetes/client/bin/{{ bin_item }}"
      dest: "{{ kubectl.bin_directory }}/{{ bin_item }}"
      mode: 0755
      remote_src: yes
    when: not kubectl_stat_result.stat.exists
    with_items:
      - kubectl
    loop_control:
      loop_var: bin_item
    tags:
      - kubectl

  - name: Test kubectl installation
    command: kubectl version --client --short
    when: kubectl_stat_result.stat.exists or not kubectl_stat_result.stat.exists
    tags:
      - molecule-idempotence-notest