kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: baf-tomas-zigardi-provider-aws-baremetal-storageclass
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  encrypted: "true"
  
