---
  - name: register temporary directory
    tempfile:
      state: directory
    register: tmp_directory
    tags:
      - molecule-idempotence-notest

  - name: check helm
    stat:
      path: "{{ helm.bin_directory }}/helm"
    register: helm_stat_result
    tags:
      - helm

  - name: Install helm
    get_url:
      url: https://storage.googleapis.com/kubernetes-helm/helm-{{ helm.version }}-{{ helm.os }}-{{ helm.arch }}.tar.gz
      dest: "{{ tmp_directory.path }}/helm.tar.gz"
      mode: 0755
      checksum: "{{ helm.checksum }}"
    register: helm_download
    when: not helm_stat_result.stat.exists
    tags:
      - helm

  - name: Unzip helm archive
    unarchive:
      src: "{{ helm_download.dest }}"
      dest: "{{ tmp_directory.path }}"
      copy: no
      mode: 0755
    when: not helm_stat_result.stat.exists
    tags:
      - helm

  - name: create bin directory
    file:
      path: "{{ helm.bin_directory }}"
      state: directory
      recurse: yes
    when: not helm_stat_result.stat.exists
    tags:
      - helm

  - name: Move helm binaries
    copy:
      src: "{{ tmp_directory.path }}/{{ helm.os }}-{{ helm.arch }}/{{ bin_item }}"
      dest: "{{ helm.bin_directory }}/{{ bin_item }}"
      mode: 0755
    with_items:
      - helm
    loop_control:
      loop_var: bin_item
    when: not helm_stat_result.stat.exists

  - name: Test helm installation
    command: helm version --client --short
    when: helm_stat_result.stat.exists or not helm_stat_result.stat.exists
    tags:
      - molecule-idempotence-notest
