###################################################################################################
# This role creates the deployment files for endorsers and pushes them to repository
###################################################################################################

  - name: "Wait for namespace creation for identities"
    include_role:
      name: check/k8_component
    vars:
      component_type: "Namespace"
      component_name: "{{ component_ns }}"

# # ---------------------------------------------------------------------
# # create image pull secrets
  - name: "Create image pull secret for identities"
    include_role:
      name: create/imagepullsecret

# ---------------------------------------------------------------------
# Create Deployment files for new Identities
  - name: "Create Deployment files"
    include_tasks: nested_main.yaml
    vars:
      component_type: "identity"
      component_name: "{{ organizationItem.name }}"
      indy_version: "indy-{{ network.version }}"
      release_dir: "{{playbook_dir}}/../../../{{organizationItem.gitops.release_dir}}/{{ organizationItem.name | lower }}"
      newIdentity: "{{ organizationItem.services.endorsers }}"
      component_ns: "{{ organizationItem.name | lower }}-ns"
      org_vault_url: "{{ organizationItem.vault.url}}"
    loop: "{{ organizations }}"
    loop_control:
      loop_var: organizationItem
    when: organizationItem is defined
