---
# Install HAProxy ingress via helmchart
- name: Install HAProxy Ingress controller
  shell: |
    KUBECONFIG={{ kubeconfig_path }} helm upgrade --install --namespace default --set metadata.namespace="ingress-controller" --set service.ports.https=8443 --set image.version="v0.6-beta.2" haproxy {{ playbook_dir }}/../../../platforms/shared/charts/haproxy
  tags:
    - haproxy

# Update external_dns with correct annotations
- name: Enable external DNS
  shell: |
    KUBECONFIG={{ kubeconfig_path }} kubectl annotate service haproxy-ingress -n ingress-controller --overwrite "external-dns.alpha.kubernetes.io/hostname=*.{{ item.external_url_suffix }}."
  tags:
    - haproxy
  when: network.env.external_dns is defined and network.env.external_dns == 'enabled'

# Wait for HAProxy pods to start running
- name: wait for pods to come up
  k8s_facts:
    kind: Pod
    namespace: ingress-controller
    kubeconfig: "{{ kubeconfig_path }}"
    context: "{{ kubecontext }}"
    label_selectors:
      - run = haproxy-ingress
    field_selectors:
      - status.phase=Running
  register: kubectl_get_pods
  until: kubectl_get_pods.resources|length > 0
  retries: "{{ network.env.retry_count}}"
  delay: 15
