---
- name: Converge
  hosts: localhost
  connection: local
  vars:
    privilege_escalate: false           #Default to NOT escalate to root privledges
    install_os: "linux"                 #Default to linux OS
    install_arch:  "amd64"              #Default to amd64 architecture
    bin_install_dir:  "~/bin"
    kubeconfig_path: "/tmp/molecule/kind-default/kubeconfig"
    kubecontext: "kind"
  roles:
    - role: setup/kubectl
      vars:
        kubectl:
          version: "1.14.2"
    - role: setup/helm
      vars:
        helm:
          version: "v2.14.1"
    - role: setup/vault
      vars:
        vault:
          version: "1.0.1"
    - role: setup/aws-auth
      vars:
        item:
          aws:
            access_key: test
            secret_key: test
    - role: setup/tiller
