
############################################################################################
# This role creates the upgrade_chaincode value file

# Check or Wait if install-chaincode is already run
---
- name: 'Check/Wait for install-chaincode job'
  k8s_facts:
    kind: "Job"
    name: installchaincode-{{ peer.name }}-{{ peer.chaincode.name }}-{{ peer.chaincode.version }}
    namespace: "{{ namespace }}"
    label_selectors:
      - "app = installchaincode-{{ peer.name }}-{{ peer.chaincode.name }}-{{ peer.chaincode.version }}"
    kubeconfig: "{{ kubernetes.config_file }}"
    context: "{{ kubernetes.context }}"
  vars:
    namespace: "{{ org.name |lower }}-net"
    kubernetes: "{{ org.k8s }}"
  loop: "{{ org.services.peers }}"
  loop_control:
    loop_var: peer
  register: component_data
  retries: "{{ network.env.retry_count}}"
  delay: 50
  until: (1 in component_data|json_query('resources[*].status.succeeded'))
  when: peer.chaincode is defined

# Nested task for chanincode upgradation
- name: "Create value file for chaincode upgrade"
  include_role:
    name: helm_component
  vars:    
    name: "{{ org.name | lower }}"
    type: "upgrade_chaincode_job"
    component_name: "upgrade-{{ org.name | lower }}-{{ peer.name }}-{{item.channel_name|lower}}-{{peer.chaincode.name}}{{peer.chaincode.version}}"
    namespace: "{{ org.name |lower }}-net"
    peer_name: "{{ peer.name }}"
    peer_address: "{{ peer.gossippeeraddress }}"    
    git_url: "{{ org.gitops.git_ssh }}"
    git_branch: "{{ org.gitops.branch }}"
    charts_dir: "{{ org.gitops.chart_source }}"
    vault: "{{ org.vault }}"
    component_chaincode: "{{ peer.chaincode }}"
    values_dir: "{{playbook_dir}}/../../../{{org.gitops.release_dir}}/{{ org.name | lower }}"
  loop: "{{ org.services.peers }}"
  loop_control:
    loop_var: peer

#Git Push : Pushes the above generated files to git directory 
- name: Git Push
  include_role: 
    name: "{{ playbook_dir }}/../../shared/configuration/roles/git_push"
  vars:
    GIT_DIR: "{{ playbook_dir }}/../../../"
    GIT_REPO: "{{ org.gitops.git_push_url }}"
    GIT_USERNAME: "{{ org.gitops.username }}"
    GIT_PASSWORD: "{{ org.gitops.password }}"
    GIT_BRANCH: "{{ org.gitops.branch }}"
    GIT_RESET_PATH: "platforms/hyperledger-fabric/configuration"
    msg: "Pushing chaincode upgrade files"