###################################################################################################
# This role creates the deployment files for indy crypto generate job and pushes them to repository
###################################################################################################
- name: "Wait for namespace creation for stewards"
  include_role:
    name: check/k8_component
  vars:
    component_type: "Namespace"
    component_name: "{{ component_ns }}"

# ---------------------------------------------------------------------
# generate indy auth_job
- name: "Create auth_job of stewards, trustee and endorser"
  include_role:
    name: create/helm_component/auth_job
  vars:
    component_type: "auth_job"
    component_name: "{{ organization }}"
    chartName: "auth_job"
    release_dir: "{{ playbook_dir }}/../../../{{ gitops.release_dir }}"

# ---------------------------------------------------------------------
# push the created deployment files to repository
- name: "Push the created deployment files to repository"
  include_role:
    name: "{{ playbook_dir }}/../../shared/configuration/roles/git_push"
  vars:
    GIT_DIR: "{{ playbook_dir }}/../../../"
    GIT_REPO: "{{ gitops.git_push_url }}"
    GIT_USERNAME: "{{ gitops.username }}"
    GIT_PASSWORD: "{{ gitops.password }}"
    GIT_BRANCH: "{{ gitops.branch }}"
    GIT_RESET_PATH: "platforms/hyperledger-indy/configuration"
    msg: "Pushing deployment files for {{ organization }}"

# ---------------------------------------------------------------------
# check Vault for correct inserted indy crypto
# - name: "Check Vault for Indy crypto"
#   include_role:
#     name: check/crypto