# This task checks if the tm crypto material is already stored in the vault or not
- name: Check if tm key is already present in the vault
  shell: |
    vault read -field=tm.key secret/{{ component_ns }}/crypto/{{ peer.name }}/transaction
  environment:
    VAULT_ADDR: "{{ vault.url }}"
    VAULT_TOKEN: "{{ vault.root_token }}"
  register: vault_tmkey_result
  ignore_errors: yes

# This task creates the build directory if it does not exist
- name: Create build directory if it does not exist
  file:
    path: build/{{ component_name }}/{{ peer.name }}
    state: directory
    mode: '0755'
    recurse: yes
  when: vault_tmkey_result.failed == True 

# This task checks if the tessera app jar exits
- name: Check if tessera jar file exists
  stat: 
    path: build/tessera-app.jar
  register: tessera_app_jar_result
  when: vault_tmkey_result.failed == True

# This task downloads the tessera jar file
- name: Download tessera jar
  get_url:
    url: https://github.com/jpmorganchase/tessera/releases/download/tessera-0.8/tessera-app-0.8-app.jar
    dest: build/tessera-app.jar
  when: vault_tmkey_result.failed == True and tessera_app_jar_result.stat.exists == False

# This task generates keys for node tm
- name: Generate node tm keys
  shell: |
    cd build/{{ component_name }}/{{ peer.name}}
    printf '\n\n' | java -jar ../../tessera-app.jar -keygen -filename tm
  when: vault_tmkey_result.failed == True

# This task copies the crypto material to the vault
- name: Copy the crypto material to Vault
  shell: |
    vault kv put secret/{{ component_ns }}/crypto/{{ peer.name }}/transaction tm.pub="$(cat build/{{ component_name }}/{{ peer.name }}/tm.pub)" tm.key="$(cat build/{{ component_name }}/{{ peer.name }}/tm.key)"
  environment:
    VAULT_ADDR: "{{ vault.url }}"
    VAULT_TOKEN: "{{ vault.root_token }}"
  when: vault_tmkey_result.failed == True
