metadata:
  namespace: 
  #uisp
  name: 
  #custodian-blockchain-indy

replicas: 
#1

network:
  name:
  #udisp

organization:
  name:
  #provider
  
image:
  initContainer: 
    name:
    #custodian-indy-node
    repository:
    #alpine:3.9.4
  indyNode: 
    name:
    #custodian-indy-node
    repository:
    #xxxx.accenture.com/uisp/indy-node-1.9.2:SR1.0.0-SNAPSHOT
  pullSecret: 
  #uisp

node:
  name:
  #indy-node
  ip:
  #0.0.0.0
  port:
  #15911
client:
  ip:
  #0.0.0.0
  port:
  #15912

service:
  ports:
    nodePort: 
    #9711
    nodeTargetPort: 
    clientPort: 
    #9712
    clientTargetPort:

configmap:
  domainGenesis:
  #
  poolGenesis:
  #

ambassador:
  #Provide annotations for ambassador service configuration
  #Only use HTTPS as HTTP and HTTPS don't work together ( https://github.com/datawire/ambassador/issues/1000 )
  #Eg.
  #  annotations: |-
  #      apiVersion: ambassador/v1
  #      kind: TCPMapping
  #      name: indy-node-node-mapping
  #      port: 9711
  #      service: custodian-blockchain-indy:9712
  #      apiVersion: ambassador/v1
  #      kind: TCPMapping
  #      name: indy-node-client-mapping
  #      port: 9712
  #      service: custodian-blockchain-indy:9712


vault:
  address: 
  #http://vault:8200
  serviceAccountName: 
  #vault-auth-provider-agent-app
  keyPath: 
  #/keys/udisp/keys/indy-node
  nodeId: 
  #indy-node

storage:
  keys:
    storagesize: 
    #512Mi
    storageClassName: 
    #ebs
  data:
    storagesize: 
    #5Gi
    storageClassName: 
    #ebs

