#############################################################################################
# This role creates configtx.yaml file which is consumed by configtxgen tool
#############################################################################################

############################################################################################
# These tasks create the configtx.yaml file as the requirements mentioned in network.yaml 
# file. The configtx.yaml file is consumed by the configtxgen binary to generate the 
# genesis block and channels.
- name: "Remove old configtx file"
  file:
    path: "{{ config_file }}"
    state: absent

# The tasks add the required data patch by patch to the configtx.yaml file to generate it.
- name: "create configtx.yaml file"
  file:
    path: "{{ config_file }}"
    state: touch

- name: "Adding init patch to configtx.yaml"
  blockinfile:
    dest: "{{ config_file }}"
    block: "{{ lookup('template', 'configtxinit.tpl') }}"
    marker: "#"

- name: "Adding organization patch to configtx.yaml"
  blockinfile:
    dest: "{{ config_file }}"
    block: "{{ lookup('template', 'configtxOrg.tpl') }}"
    marker: "#"
  vars:    
    component_name: "{{ item.name }}"
    component_ns: "{{ item.name | lower }}-net"
    component_type: "{{ item.type | lower }}"
  loop: "{{ network['organizations'] }}"

- name: "Adding orderer patch to configtx.yaml"
  blockinfile:
    dest: "{{ config_file }}"
    block: "{{ lookup('template', 'configtxOrderer.tpl') }}"
    marker: "#"
  vars:
    orderers: "{{ item.services.orderers }}"
    consensus: "{{ item.services.consensus }}"
    component_ns: "{{ item.name | lower }}-net"
  loop: "{{ network['organizations'] }}"
  when: item.type == 'orderer'

- name: "Adding profile patch to configtx.yaml"
  blockinfile:
    dest: "{{ config_file }}"
    block: "{{ lookup('template', 'configtxProfile.tpl') }}"
    marker: "#"
  when: network.channels is defined
