---
tmp_directory: "{{ lookup('env', 'TMPDIR') | default('/tmp',true) }}"
release_version: "{{ release | regex_replace('.','') }}"
constellation:
  repo: https://github.com/jpmorganchase/constellation/releases/download/v{{version}}/constellation-{{version}}-ubuntu{{release_version}}.tar.xz
