############################################################################################
# This task creates the json file for the anchor peer update
############################################################################################

# remove old anchor file
- name: Remove old anchor file
  file:
    path: "{{ build_path }}/channel-artifacts/{{ channel_name | lower}}-anchorfile.json"
    state: absent
# creating new anchor file
- name: Creating new anchor file
  file:
    path: "{{ build_path }}/channel-artifacts/{{ channel_name | lower}}-anchorfile.json"
    state: touch

# Create the values for anchor peer update
- name: "adding new org peers anchor peer information"
  shell: |
    if [ -s {{ build_path }}/channel-artifacts/{{ channel_name | lower}}-anchorfile.json ]
    then
        echo -n "," >> {{ build_path }}/channel-artifacts/{{ channel_name | lower}}-anchorfile.json  
    fi
    echo -n "{\"host\":\"{{ peer.gossippeeraddress.split(":")[0] | to_json }}\",\"port\":{{ peer.gossippeeraddress.split(":")[1] | to_json }}}" >> {{ build_path }}/channel-artifacts/{{ channel_name | lower}}-anchorfile.json
  loop: "{{ org.services.peers }}"
  loop_control:
    loop_var: peer
  when: peer.type == 'anchor'
