# This task checks if the crypto material is already stored in the vault or not
- name: Check if nodekey already present in the vault
  shell: |
    vault read -field=nodekey secret/{{ component_ns }}/crypto/{{ peer.name }}/quorum
  environment:
    VAULT_ADDR: "{{ vault.url }}"
    VAULT_TOKEN: "{{ vault.root_token }}"
  register: vault_nodekey_result
  ignore_errors: yes

# This variable will have a value greater than zero if the nodekey of any of the node is missing
- name: vault_check variable
  set_fact:
    vault_check={{ vault_check|default(0) | int + 1 }}
  when: vault_nodekey_result.failed == False
  