#Call nested_nodekey_vault_check.yaml for checking if nodekey for each node is present or not
- name: Call nested check for each node
  include_tasks: nested_nodekey_vault_check.yaml
  loop: "{{ org.services.peers }}"
  loop_control:
    loop_var: peer
